# Generated by Django 5.0 on 2023-12-15 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('lesson_type', models.CharField(blank=True, max_length=20)),
                ('teacher', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('semester', models.IntegerField(blank=True)),
                ('lesson_number', models.IntegerField(blank=True)),
                ('image_url', models.ImageField(default='images/publications/ладно.jpg', upload_to='images/publications')),
                ('main_file_url', models.FileField(null=True, upload_to='files/publications')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
