# Generated by Django 5.0 on 2023-12-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_tag_publication_other_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
