# Generated by Django 5.0 on 2023-12-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image_url',
            field=models.ImageField(default='images/publications/ладно.jpg', null=True, upload_to='images/publications'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='lesson_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='lesson_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='other_tags',
            field=models.ManyToManyField(null=True, to='publications.tag'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
