# Generated by Django 5.0 on 2023-12-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_publication_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image_url',
            field=models.ImageField(default='media/images/ok.jpg', null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='main_file_url',
            field=models.FileField(null=True, upload_to='media/files'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='other_tags',
            field=models.ManyToManyField(blank=True, null=True, to='publications.tag'),
        ),
    ]
