# Generated by Django 5.0 on 2023-12-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_remove_publication_lesson_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='posted_by',
            new_name='user',
        ),
    ]
